language: r
sudo: required
cache: packages
r_github_packages:
  - VPetukhov/ggrastr
  - Japrin/sscVis
  - Japrin/SC3
bioc_packages:
  - SingleCellExperiment
  - BiocGenerics
  - BiocParallel
  - ComplexHeatmap
  - scran
  - uwot

addons:
  apt:
    packages:
    - libgsl0-dev
