# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  global:
   R_ARCH: x64
   USE_RTOOLS: true
  matrix:
   - R_VERSION: stable
  PKGTYPE: both
  BIOC_USE_DEVEL: FALSE

build_script:
  - travis-tool.sh r_binary_install BiocManager lifecycle
  - travis-tool.sh install_bioc SingleCellExperiment scran BiocGenerics BiocParallel ComplexHeatmap
  - travis-tool.sh install_github Japrin/SC3
  - travis-tool.sh install_deps
  - travis-tool.sh install_bioc_deps
#  - travis-tool.sh r_binary_install curl pkgmaker


test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
